package com.example.cozybench.model.enums;

import com.example.cozybench.model.TypeEnumInterface;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum WindowMaterialTypeEnum implements TypeEnumInterface {
    WINDOW_MATERIAL_SIMPLE_GLAZING_SYSTEM("WINDOWMATERIAL:SIMPLEGLAZINGSYSTEM"),

    WINDOW_MATERIAL_GLAZING("WINDOWMATERIAL:GLAZING"),

    WINDOW_MATERIAL_GAS("WINDOWMATERIAL:GAS"),

    WINDOW_MATERIAL_GAS_MIXTURE("WINDOWMATERIAL:GASMIXTURE"),

    WINDOW_MATERIAL_BLIND("WINDOWMATERIAL:BLIND"),

    WINDOW_MATERIAL_DAYLIGHT_REDIRECTION_DEVICE("WINDOWMATERIAL:DAYLIGHTREDIRECTIONDEVICE"),

    WINDOW_MATERIAL_SCREEN("WINDOWMATERIAL:SCREEN"),

    WINDOW_MATERIAL_SHADE("WINDOWMATERIAL:SHADE"),

    WINDOW_MATERIAL_GLAZING_REFRACTION_EXTINCTION_METHOD("WINDOWMATERIAL:GLAZING:REFRACTIONEXTINCTIONMETHOD");

    @Getter
    private final String eppyName;
}
